forward
global type u_tabpg_dwproperty_srvlinkage2 from pfc_u_tabpg_dwproperty_srvlinkage2
end type
end forward

global type u_tabpg_dwproperty_srvlinkage2 from pfc_u_tabpg_dwproperty_srvlinkage2
end type
global u_tabpg_dwproperty_srvlinkage2 u_tabpg_dwproperty_srvlinkage2

on u_tabpg_dwproperty_srvlinkage2.create
call pfc_u_tabpg_dwproperty_srvlinkage2::create
end on

on u_tabpg_dwproperty_srvlinkage2.destroy
call pfc_u_tabpg_dwproperty_srvlinkage2::destroy
end on

