forward
global type u_tabpg_dwproperty_srvsyntax from pfc_u_tabpg_dwproperty_srvsyntax
end type
end forward

global type u_tabpg_dwproperty_srvsyntax from pfc_u_tabpg_dwproperty_srvsyntax
end type
global u_tabpg_dwproperty_srvsyntax u_tabpg_dwproperty_srvsyntax

on u_tabpg_dwproperty_srvsyntax.create
call pfc_u_tabpg_dwproperty_srvsyntax::create
end on

on u_tabpg_dwproperty_srvsyntax.destroy
call pfc_u_tabpg_dwproperty_srvsyntax::destroy
end on

