forward
global type u_tabpg_dwproperty_srvreport from pfc_u_tabpg_dwproperty_srvreport
end type
end forward

global type u_tabpg_dwproperty_srvreport from pfc_u_tabpg_dwproperty_srvreport
end type
global u_tabpg_dwproperty_srvreport u_tabpg_dwproperty_srvreport

on u_tabpg_dwproperty_srvreport.create
call pfc_u_tabpg_dwproperty_srvreport::create
end on

on u_tabpg_dwproperty_srvreport.destroy
call pfc_u_tabpg_dwproperty_srvreport::destroy
end on

