forward
global type u_tabpg_dwproperty_srvlinkage from pfc_u_tabpg_dwproperty_srvlinkage
end type
end forward

global type u_tabpg_dwproperty_srvlinkage from pfc_u_tabpg_dwproperty_srvlinkage
end type
global u_tabpg_dwproperty_srvlinkage u_tabpg_dwproperty_srvlinkage

on u_tabpg_dwproperty_srvlinkage.create
call pfc_u_tabpg_dwproperty_srvlinkage::create
end on

on u_tabpg_dwproperty_srvlinkage.destroy
call pfc_u_tabpg_dwproperty_srvlinkage::destroy
end on

