forward
global type u_tabpg_dwproperty_srvprintpreview from pfc_u_tabpg_dwproperty_srvprintpreview
end type
end forward

global type u_tabpg_dwproperty_srvprintpreview from pfc_u_tabpg_dwproperty_srvprintpreview
end type
global u_tabpg_dwproperty_srvprintpreview u_tabpg_dwproperty_srvprintpreview

on u_tabpg_dwproperty_srvprintpreview.create
call pfc_u_tabpg_dwproperty_srvprintpreview::create
end on

on u_tabpg_dwproperty_srvprintpreview.destroy
call pfc_u_tabpg_dwproperty_srvprintpreview::destroy
end on

