forward
global type u_tabpg_dwproperty_srvcalculator from pfc_u_tabpg_dwproperty_srvcalculator
end type
end forward

global type u_tabpg_dwproperty_srvcalculator from pfc_u_tabpg_dwproperty_srvcalculator
end type
global u_tabpg_dwproperty_srvcalculator u_tabpg_dwproperty_srvcalculator

on u_tabpg_dwproperty_srvcalculator.create
call pfc_u_tabpg_dwproperty_srvcalculator::create
end on

on u_tabpg_dwproperty_srvcalculator.destroy
call pfc_u_tabpg_dwproperty_srvcalculator::destroy
end on

